name: Cypress Tests

on: push

jobs:
  npx cypress run --record --key 17ab3a4e-3204-471a-abaa-d6ec11f3e87c:
    runs-on: ubuntu-22.04
    browser: chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 
        uses: cypress-io/github-action@v5
        with:
          
